# Site settings
baseurl 		= "https://abhinavrahul.github.io/"
theme 			= "cocoa-eh"
languageCode 	= "en-us"
author 			= "Abhinav Rahul"
title 			= "IndusOcean"
enableEmoji 	= true

[taxonomies]
tag 			= "tags"
category 		= "categories"
series 			= "series"

[params]
dateform 		= "Jan 02, 2006"
dateformfull 	= "Mon Jan 02 2006 15:04:05 MST"
description 	= "Personal website"
copyright 		= "Copyright © 2017 Abhinav Rahul"
logofile 		= "img/monkey.jpg"
extracssfiles 	= [ "css/message.css", "css/gallery.css", "css/cocoa-eh-fixes.css" ]
highlightjs 	= true
progressively 	= false
latestpostcount = 3
posts_navigation= true
github 			= "abhinavrahul"
email 			= "abhinavrahul.iitkgp@gmail.com"
twitter			= "_abhinavrahul"
